version: "3"
services:
  # selenium-hub:
  #   image: selenium/hub:${SELENIUM_VERSION}

  # chrome:
  #   image: selenium/node-chrome:${SELENIUM_VERSION}
  #   volumes:
  #     - /dev/shm:/dev/shm
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  #     - START_XVFB=false
  #   depends_on: 
  #     - selenium-hub
  #   ports:
  #     - "5555:5555"

  node:
    image: registry.ql6625.fr/general-bdd-testing:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /dev/shm:/dev/shm
      - ./report:/usr/app/report
    environment:
      - HUB_PROTOCOL=https
      - HUB_HOST=selenium.ql6625.fr
      - HUB_PORT=443
    # depends_on:
    #   - chrome
